services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipy-ai
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    restart: always
    image: ${DOCKER_IMAGE}:latest